language: node_js
node_js:
  - 0.10

branches:
  only:
    - master

before_install:
  - npm install -g grunt-cli
  - sudo cat /etc/sudoers

script:
  - sudo -E grunt

notifications:
  email:
    - mrvisser@gmail.com