language: node_js
node_js:
  - 0.10

branches:
  only:
    - master

before_install:
  - npm install -g grunt-cli

script:
  - echo $NVM_BIN > /tmp/.nvm_bin
  - ls -a ~
  - sudo `cat /tmp/.nvm_bin`/grunt

notifications:
  email:
    - mrvisser@gmail.com